DROP TABLE class_syndrome;
CREATE TABLE class_syndrome (
	syndrome_id SERIAL,
	syndrome_player_id INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
