DROP TABLE mobile;
CREATE TABLE mobile (
	mob_id SERIAL,
	mob_virtual_number INTEGER NOT NULL,
	mob_name VARCHAR(256) NOT NULL,
	mob_short_description VARCHAR(64) NOT NULL,
	mob_long_description VARCHAR(512) NOT NULL,
	mob_description TEXT,
	mob_action_bitvector VARCHAR(2) NOT NULL,
	mob_affection_bitvector VARCHAR(2) NOT NULL,
	mob_ability_strength INTEGER NOT NULL,
	mob_ability_strength_add INTEGER NOT NULL,
	mob_ability_intelligence INTEGER NOT NULL,
	mob_ability_wisdom INTEGER NOT NULL,
	mob_ability_dexterity INTEGER NOT NULL,
	mob_ability_constitution INTEGER NOT NULL,
	mob_ability_charisma INTEGER NOT NULL,
	mob_alignment INTEGER NOT NULL,
	mob_attack_type INTEGER NOT NULL,
	mob_level INTEGER NOT NULL,
	mob_hitroll INTEGER NOT NULL,
	/* mob_thac0 INTEGER NOT NULL, */
	/* mob_armor_class VARCHAR(2) NOT NULL, */
	mob_armor INTEGER NOT NULL,
	mob_max_hitpoints INTEGER NOT NULL,
	mob_max_mana INTEGER NOT NULL,
	mob_max_move INTEGER NOT NULL,
	/* mob_barehand_damage INTEGER NOT NULL, */
	mob_gold INTEGER NOT NULL,
	mob_exp INTEGER NOT NULL,
	mob_load_position INTEGER NOT NULL, 
	mob_default_position INTEGER NOT NULL, 
	mob_sex INTEGER NOT NULL,
	mob_hitpoints INTEGER,
	mob_mana INTEGER NOT NULL,
	mob_move INTEGER NOT NULL,
	mob_damnodice INTEGER NOT NULL,
	mob_damsizedice INTEGER NOT NULL,
	mob_damroll INTEGER NOT NULL,
	mob_weight INTEGER NOT NULL,
	mob_height INTEGER NOT NULL,
	mob_class INTEGER NOT NULL
);
