CREATE TABLE mobile (
	id SERIAL,
	virtual_number INTEGER NOT NULL,
	name VARCHAR(256) NOT NULL,
	short_description VARCHAR(64) NOT NULL,
	long_description VARCHAR(512) NOT NULL,
	description TEXT,
	action_bitvector VARCHAR(2) NOT NULL,
	affection_bitvector VARCHAR(2) NOT NULL,
	ability_strength INTEGER NOT NULL,
	ability_intelligence INTEGER NOT NULL,
	ability_wisdom INTEGER NOT NULL,
	ability_dexterity INTEGER NOT NULL,
	ability_constitution INTEGER NOT NULL,
	ability_charisma INTEGER NOT NULL,
	alignment INTEGER NOT NULL,
	type_flag VARCHAR(2),
	mob_level INTEGER NOT NULL,
	hitroll INTEGER NOT NULL,
	thac0 INTEGER NOT NULL,
	armor_class VARCHAR(2) NOT NULL,
	max_hitpoints INTEGER NOT NULL,
	max_mana INTEGER NOT NULL,
	max_move INTEGER NOT NULL,
	barehand_damage INTEGER NOT NULL,
	gold INTEGER NOT NULL,
	experience_points INTEGER NOT NULL,
	load_position VARCHAR(2),
	default_position VARCHAR(2),
	sex INTEGER NOT NULL,
	hitpoints INTEGER,
	mana INTEGER NOT NULL,
	move INTEGER NOT NULL,
	dam_no_dice INTEGER NOT NULL,
	dam_size_dice INTEGER NOT NULL,
	dam_roll INTEGER NOT NULL,
	weight INTEGER NOT NULL,
	height INTEGER NOT NULL,
	mob_class INTEGER NOT NULL
);
