CREATE TABLE player (
	player_id SERIAL,
	player_virtual_number INTEGER NOT NULL,
	player_name VARCHAR(256) NOT NULL,
	player_short_description VARCHAR(64) NOT NULL,
	player_long_description VARCHAR(512) NOT NULL,
	player_description TEXT,
	player_action_bitvector VARCHAR(2) NOT NULL,
	player_affection_bitvector VARCHAR(2) NOT NULL,
	player_ability_strength INTEGER NOT NULL,
	player_ability_strength_add INTEGER NOT NULL,
	player_ability_intelligence INTEGER NOT NULL,
	player_ability_wisdom INTEGER NOT NULL,
	player_ability_dexterity INTEGER NOT NULL,
	player_ability_constitution INTEGER NOT NULL,
	player_ability_charisma INTEGER NOT NULL,
	player_alignment INTEGER NOT NULL,
	player_attack_type INTEGER NOT NULL,
	player_level INTEGER NOT NULL,
	player_hitroll INTEGER NOT NULL,
	player_armor INTEGER NOT NULL,
	player_max_hitpoints INTEGER NOT NULL,
	player_max_mana INTEGER NOT NULL,
	player_max_move INTEGER NOT NULL,
	player_gold INTEGER NOT NULL,
	player_exp INTEGER NOT NULL,
	player_sex INTEGER NOT NULL,
	player_hitpoints INTEGER,
	player_mana INTEGER NOT NULL,
	player_move INTEGER NOT NULL,
	player_damnodice INTEGER NOT NULL,
	player_damsizedice INTEGER NOT NULL,
	player_damroll INTEGER NOT NULL,
	player_weight INTEGER NOT NULL,
	player_height INTEGER NOT NULL,
	player_class INTEGER NOT NULL
);
