#!/usr/bin/expect -f
####### ####### #######
#       #     # #     #
#       #     # #     #
#####   #     # #     #
#       #     # #     #
#       #     # #     #
#       ####### #######

spawn nc localhost 4000
expect "By what name do you wish to be known?" { send "Foo\r\n" }
expect "Password:" { send "far\r\n" }
expect "*** PRESS RETURN:" { send "\r\n" }
expect " Make your choice:" { send "1\r\n" }
expect "Far says, 'it is time...'" {  send "say Indeed, brother. Commence the operation.\r\n" }
expect "Far says, 'Commencing...'\r" { send_user "Commencing drone test suite\r\n" }
	expect ">" {  send_user "prompt" } 
 	expect "You have been spotted." { 
		send "say spotted\r"
	}
	expect "You say, 'spotted'" {
		send "shout Far complete\r"
	}
sleep 1
interact

