#ifndef __MENTOC_MODS_ITEM_TYPES__
#define __MENTOC_MODS_ITEM_TYPES__
#include <boost/preprocessor.hpp>
#define MENTOC_ITEM_TYPES_SEQ (rifle)(explosive)(drone)(gadget)(attachment)(armor)
#define MENTOC_ITEM_TYPES_SEQ_CAPS (ITEM_RIFLE)(ITEM_EXPLOSIVE)(ITEM_DRONE)(ITEM_GADGET)(ITEM_ATTACHMENT)(ITEM_ARMOR)
#define MENTOC_YAML_DESC_IMPL(r,data,T) struct BOOST_PP_CAT(T,_description_t);

#define MENTOC_USING_CT_IMPL(r,data,CLASS_TYPE)\
using BOOST_PP_CAT(mw_,CLASS_TYPE) = mods::weapon::type::CLASS_TYPE;

#define MENTOC_USING_CT \
BOOST_PP_SEQ_FOR_EACH(MENTOC_USING_CT_IMPL, ~, MENTOC_ITEM_TYPES_SEQ)

#define MENTOC_YAML_DESC \
BOOST_PP_SEQ_FOR_EACH(MENTOC_YAML_DESC_IMPL, ~, MENTOC_ITEM_TYPES_SEQ)

#define MENTOC_DECLARE_DATA_STRUCTS_IMPL(r,data,CLASS_TYPE)\
struct BOOST_PP_CAT(CLASS_TYPE,_data_t);

#define MENTOC_DECLARE_DATA_STRUCTS \
BOOST_PP_SEQ_FOR_EACH(MENTOC_DECLARE_DATA_STRUCTS_IMPL, ~, MENTOC_ITEM_TYPES_SEQ)

#define MENTOC_OBJ_DATA_FEED_SWITCH_IMPL(r,data,CLASS_TYPE)\
	case CLASS_TYPE: if(obj_file.length() == 0){\
										 obj_file = default_yaml_file( BOOST_PP_STRINGIZE(BOOST_PP_ELEM(r,MENTOC_ITEM_TYPES_SEQ)) );\
			 }; BOOST_PP_ARRAY_ELEM(r,MENTOC_ITEM_TYPES_SEQ)->init(this); break;

#define MENTOC_OBJ_DATA_FEED_SWITCH \
BOOST_PP_SEQ_FOR_EACH(MENTOC_OBJ_DATA_FEED_SWITCH_IMPL, ~, MENTOC_ITEM_TYPES_SEQ_CAPS)
#endif
