[bool]
ALLOW_MOCK_LEVELS,false

[int]
FIRE_DAMAGE_TICK_RESOLUTION,30
FLASHBANG_COOLDOWN_TICKS,3
FIRE_EVERY_N_TICKS,400
FIRE_WOODEN_ADDITIONAL_TICKS,80
FIRE_CARPET_ADDITIONAL_TICKS,60
DAMAGE_DIVISOR,3
FRAG_GRENADE_TICKS,6
EMP_GRENADE_TICKS,6
SENSOR_GRENADE_TICKS,6
FLASHBANG_GRENADE_TICKS,6
SMOKE_GRENADE_TICKS,6
INCENDIARY_GRENADE_TICKS,6
FIRE_STATUS_KINDLING_DAMAGE,10
FIRE_STATUS_COMPLETELY_ON_FIRE_DAMAGE,70
FIRE_STATUS_SMOLDERING_DAMAGE,40
FIRE_STATUS_SMOKING_DAMAGE,15
ADVANCE_LEVEL_BONUS_HP_DICE,6
ADVANCE_LEVEL_BONUS_HP_SIDES,6
ADVANCE_LEVEL_BONUS_HP_THRESHOLD,12

[uint16_t]
LOWLY_SECURITY_ROAM_TICK,20
LOWLY_SECURITY_RANDOM_TRIVIAL_TICK,60
BREACHER_EXPLOSIVE_SHOT_MAX_COUNT,2
SKILL_GHOST_DRONE_SCAN,50
SKILL_GHOST_STEALTH,50
SKILL_GHOST_SUMMON_EXTRACTION,50
SKILL_GHOST_XRAY_SHOT,50
SKILL_GHOST_FEIGN_DEATH,50
SKILL_GHOST_PLANT_CLAYMORE,50
SKILL_GHOST_PENETRATING_SHOT,50
SKILL_GHOST_INTIMIDATION,50
SKILL_GHOST_CRYOGENIC_GRENADE,50
SKILL_GHOST_FLASH_UNDERBARREL,50
SKILL_SNIPER_TRACKING_SHOT,50
SKILL_SNIPER_SUMMON_UNDERBARREL_SHOTGUN,50
SKILL_SNIPER_SUMMON_UNDERBARREL_GRENADE_LAUNCHER,50
SKILL_SNIPER_GUIDED_MISSILE,50
SKILL_SNIPER_TARGET_LIMB,50
SKILL_SNIPER_PLANT_CLAYMORE,50
SKILL_SNIPER_XRAY_SHOT,50
SKILL_SNIPER_SUMMON_AREA_SCAN,50
SKILL_GRENADE_USAGE,50
SKILL_CLAYMORE_USAGE,50
SKILL_BREACH_USAGE,50
WSL_SHOTGUN_0_ALLOWABLE,1
WSL_SHOTGUN_0_ACCURACY,80
WSL_SHOTGUN_0_DAMAGE,80
WSL_SHOTGUN_1_ALLOWABLE,1
WSL_SHOTGUN_1_ACCURACY,15
WSL_SHOTGUN_1_DAMAGE,15
WSL_SHOTGUN_2_ALLOWABLE,0
WSL_SHOTGUN_2_ACCURACY,0
WSL_SHOTGUN_2_DAMAGE,0
WSL_SHOTGUN_3_ALLOWABLE,0
WSL_SHOTGUN_3_ACCURACY,0
WSL_SHOTGUN_3_DAMAGE,0
WSL_SHOTGUN_4_ALLOWABLE,0
WSL_SHOTGUN_4_ACCURACY,0
WSL_SHOTGUN_4_DAMAGE,0
WSL_AR_0_ALLOWABLE,1
WSL_AR_0_ACCURACY,40
WSL_AR_0_DAMAGE,40
WSL_AR_1_ALLOWABLE,1
WSL_AR_1_ACCURACY,40
WSL_AR_1_DAMAGE,40
WSL_AR_2_ALLOWABLE,1
WSL_AR_2_ACCURACY,40
WSL_AR_2_DAMAGE,40
WSL_AR_3_ALLOWABLE,0
WSL_AR_3_ACCURACY,0
WSL_AR_3_DAMAGE,0
WSL_AR_4_ALLOWABLE,0
WSL_AR_4_ACCURACY,0
WSL_AR_4_DAMAGE,0
WSL_SMG_0_ALLOWABLE,1
WSL_SMG_0_ACCURACY,90
WSL_SMG_0_DAMAGE,40
WSL_SMG_1_ALLOWABLE,0
WSL_SMG_1_ACCURACY,0
WSL_SMG_1_DAMAGE,0
WSL_SMG_2_ALLOWABLE,0
WSL_SMG_2_ACCURACY,0
WSL_SMG_2_DAMAGE,0
WSL_SMG_3_ALLOWABLE,0
WSL_SMG_3_ACCURACY,0
WSL_SMG_3_DAMAGE,0
WSL_SMG_4_ALLOWABLE,0
WSL_SMG_4_ACCURACY,0
WSL_SMG_4_DAMAGE,0
WSL_MACHINE_PISTOL_0_ALLOWABLE,1
WSL_MACHINE_PISTOL_0_ACCURACY,25
WSL_MACHINE_PISTOL_0_DAMAGE,15
WSL_MACHINE_PISTOL_1_ALLOWABLE,0
WSL_MACHINE_PISTOL_1_ACCURACY,0
WSL_MACHINE_PISTOL_1_DAMAGE,0
WSL_MACHINE_PISTOL_2_ALLOWABLE,0
WSL_MACHINE_PISTOL_2_ACCURACY,0
WSL_MACHINE_PISTOL_2_DAMAGE,0
WSL_MACHINE_PISTOL_3_ALLOWABLE,0
WSL_MACHINE_PISTOL_3_ACCURACY,0
WSL_MACHINE_PISTOL_3_DAMAGE,0
WSL_MACHINE_PISTOL_4_ALLOWABLE,0
WSL_MACHINE_PISTOL_4_ACCURACY,0
WSL_MACHINE_PISTOL_4_DAMAGE,0
HEADSHOT_DIVISOR,3
WSL_HANDGUN_0_ALLOWABLE,1
WSL_HANDGUN_0_ACCURACY,55
WSL_HANDGUN_0_DAMAGE,10
WSL_HANDGUN_1_ALLOWABLE,0
WSL_HANDGUN_1_ACCURACY,0
WSL_HANDGUN_1_DAMAGE,0
WSL_HANDGUN_2_ALLOWABLE,0
WSL_HANDGUN_2_ACCURACY,0
WSL_HANDGUN_2_DAMAGE,0
WSL_HANDGUN_3_ALLOWABLE,0
WSL_HANDGUN_3_ACCURACY,0
WSL_HANDGUN_3_DAMAGE,0
WSL_HANDGUN_4_ALLOWABLE,0
WSL_HANDGUN_4_ACCURACY,0
WSL_HANDGUN_4_DAMAGE,0
WSL_LMG_0_ALLOWABLE,1
WSL_LMG_0_ACCURACY,40
WSL_LMG_0_DAMAGE,40
WSL_LMG_1_ALLOWABLE,1
WSL_LMG_1_ACCURACY,35
WSL_LMG_1_DAMAGE,35
WSL_LMG_2_ALLOWABLE,1
WSL_LMG_2_ACCURACY,30
WSL_LMG_2_DAMAGE,30
WSL_LMG_3_ALLOWABLE,0
WSL_LMG_3_ACCURACY,0
WSL_LMG_3_DAMAGE,0
WSL_LMG_4_ALLOWABLE,0
WSL_LMG_4_ACCURACY,0
WSL_LMG_4_DAMAGE,0
WSL_SNIPER_0_ALLOWABLE,1
WSL_SNIPER_0_ACCURACY,10
WSL_SNIPER_0_DAMAGE,10
WSL_SNIPER_1_ALLOWABLE,1
WSL_SNIPER_1_ACCURACY,35
WSL_SNIPER_1_DAMAGE,35
WSL_SNIPER_2_ALLOWABLE,1
WSL_SNIPER_2_ACCURACY,60
WSL_SNIPER_2_DAMAGE,60
WSL_SNIPER_3_ALLOWABLE,1
WSL_SNIPER_3_ACCURACY,75
WSL_SNIPER_3_DAMAGE,75
WSL_SNIPER_4_ALLOWABLE,1
WSL_SNIPER_4_ACCURACY,75
WSL_SNIPER_4_DAMAGE,75
SKILL_CAMERA_PLACEMENT,50
SKILL_DETECT_CAMERAS,50
SKILL_CAMERA_DESTRUCTION,100
SKILL_ELECTRIFIED_DAMAGE,100
SKILL_PROTECT_FROM_EMP,200
SKILL_CREATE_EMP_WEAPONS,200
SKILL_COUNTER_SHOCK,4
SKILL_TOGGLE_THERMAL,2050
SKILL_TOGGLE_NIGHT_VISION,2050
SKILL_HEADGEAR_INTROSPECTION,3050
SKILL_PROXIMITY_ALARM,3050
SKILL_DEPLOYABLE_TURRET,3050
SKILL_DEPLOYABLE_FIRE_TURRET,3050
SKILL_DOOR_CAMERA,3050
SKILL_BASIC_ARMOR,50
SKILL_ADVANCED_ARMOR,50
SKILL_ELITE_ARMOR,50
SKILL_THIEF,200
SKILL_MOLD,350
SKILL_NO_FACTOR_BASIC,400
SKILL_NO_FACTOR_ADVANCED,850
SKILL_NO_FACTOR_ELITE,900
SKILL_EXPLOSIVE_RESISTANCE,2050
SKILL_INJURE_RESISTANCE,3050
SKILL_MUNITIONS_REFLECTOR,4
SKILL_SENTINEL_DISCIPLINE,3
SKILL_DEPLOYABLE_SHIELD,8050
SKILL_SPRAY_CHANCE,150
SKILL_HEADSHOT_CHANCE,250
SKILL_LIMB_CHANCE,350
SKILL_BETTER_SNIPING_ACCURACY,450
SKILL_TARGET_LIMB,850
SKILL_ACCURACY,150
SKILL_VIP,250
SKILL_TRACKER,350
SKILL_QUIETER_SNIPER_SHOTS,350
SKILL_FASTER_BREACHES,50
SKILL_FURTHER_C4S,4
SKILL_STRONGER_FRAG_ARM,50
SKILL_BIGGER_CLAYMORES,50
SKILL_FASTER_THERMITES,50
SKILL_BIGGER_FIRE_NADES,50
SKILL_CRAFTY_C4,4
SKILL_BETTER_EXPLOSIONS,33
SKILL_RETROFIT_GRENADE_LAUNCHER,50
SKILL_RETROFIT_FIRE_GRENADE_LAUNCHER,50
SKILL_RETROFIT_SMOKE_GRENADE_LAUNCHER,50
SKILL_RETROFIT_SENSOR_GRENADE_LAUNCHER,50
SKILL_RETROFIT_STUN_GRENADE_LAUNCHER,50
SKILL_STEROID_DEALER,50
SKILL_HGH_DEALER,50
SKILL_NOXIOUS_NADE_CRAFTER,50
SKILL_DUTCH_OVEN,50
SKILL_FIRE_NADE_DEALER,50
SKILL_PRO_WEAPON_HANDLER,50
SKILL_BETTER_WEAPON_ACCURACY,50
SKILL_FASTER_TRIGGER_FINGER,50
SKILL_FASTER_RELOADING,50
SKILL_BASIC_PISTOL,150
SKILL_BASIC_ASSAULT_RIFLE,150
SKILL_BASIC_SHOTGUN,150
SKILL_BASIC_SNIPER_RIFLE,150
SKILL_BASIC_SUB_MACHINE_GUN,150
SKILL_INTERMEDIATE_PISTOL,150
SKILL_INTERMEDIATE_ASSAULT_RIFLE,150
SKILL_INTERMEDIATE_SHOTGUN,150
SKILL_INTERMEDIATE_SNIPER_RIFLE,150
SKILL_INTERMEDIATE_SUB_MACHINE_GUN,150
SKILL_ADVANCED_PISTOL,150
SKILL_ADVANCED_ASSAULT_RIFLE,150
SKILL_ADVANCED_SHOTGUN,150
SKILL_ADVANCED_SNIPER_RIFLE,150
SKILL_ADVANCED_SUB_MACHINE_GUN,150
SKILL_EXPERT_PISTOL,150
SKILL_EXPERT_ASSAULT_RIFLE,150
SKILL_EXPERT_SHOTGUN,150
SKILL_EXPERT_SNIPER_RIFLE,150
SKILL_EXPERT_SUB_MACHINE_GUN,150
SKILL_ARMOR_PENETRATION_SHOT,150
SKILL_NONSTOP_PENETRATION_SHOT,150
SKILL_INCREASED_INJURE_CHANCE,150
SKILL_ASSAULT_RIFLE_SHRAPNEL,150
SKILL_ENTRY_DENIAL,2050
SKILL_MISDIRECTION,2050
SKILL_SNIPER_SUPPORT,2050
SKILL_REDUCED_DETECTION_CHANCE,4
SKILL_INCREASED_AWARENESS,2050
SKILL_TRICK_MAGAZINE,2050
SKILL_CHAINABLE_BREACHING,1
SKILL_HGH_MORE_POWERFUL,2050
SKILL_BASIC_HP_RECOVERY,2050
SKILL_PARASITIC_HP_RECOVERY,2050
SKILL_SUTURE,2050
SKILL_ADRENALINE_BOOST,2050
GHOST_FEIGN_DEATH_BLOCKED_FOR_TICKS,60
PYREXIA_FIRE_NADE_RECHARGE_TICKS_INITIATE,390
PYREXIA_FIRE_NADE_RECHARGE_TICKS_FAMILIAR,280
PYREXIA_FIRE_NADE_RECHARGE_TICKS_MASTER,170
GHOST_PLANT_CLAYMORE_INITIATE_MOD_CALL_COUNT,10
GHOST_PLANT_CLAYMORE_FAMILIAR_MOD_CALL_COUNT,8
GHOST_PLANT_CLAYMORE_MASTER_MOD_CALL_COUNT,5
SKILL_PYREXIA_THROW_FIRE_NADE,50
SKILL_PYREXIA_DRENCH_IN_GASOLINE,50
SKILL_PYREXIA_DRENCH_ROOM_IN_GASOLINE,50
SKILL_PYREXIA_CONVERT_TO_FIRE_NADE,50
SKILL_PYREXIA_ATTACH_INC_LAUNCHER,50
SKILL_PYREXIA_ATTACH_FLAMETHROWER,50
SKILL_PYREXIA_CREATE_WALL_OF_FIRE,50
SKILL_PYREXIA_SEAL_OFF_ROOM,50
SKILL_SNIPER_TRACKING_SHOT_TICKS,280

[float]
ADVANCE_LEVEL_HP_FLOAT_MULTIPLIER,2.5
EXPLOSIVE_CRITICAL_MULTIPLIER,0.75
RIFLE_CRITICAL_MULTIPLIER,0.75
INJURED_MAX_HP_MULTIPLIER,0.10
MINI_GUNNER_DECREASED_SIGHT_MULTIPLIER,0.75
CHANCE_TO_INJURE_SKILL_MODIFIER,3.75
INJURE_RESISTANCE_SKILL_MODIFIER,2.75
ASSAULT_RIFLE_SHRAPNEL_SKILL_DAMAGE_MULTIPLIER,0.33
BONUS_STRENGTH_MULTIPLIER,0.25
CONSTITUTION_STRENGTH_DAMPENER_MULTIPLIER,0.13
WEAPON_COOLDOWN_MODIFIER_TIER_ONE,0.032
WEAPON_COOLDOWN_MODIFIER_TIER_TWO,0.05813
WEAPON_COOLDOWN_MODIFIER_TIER_THREE,0.12893

[std::string]
CAN_BE_SEARCHED,"This command can be searched by typing the command followed by a space and a word that you would like to search for."
SANITY_CHECK,"sanity-check"
MINI_GUNNER_WEAR_LIGHT,""
MINI_GUNNER_WEAR_FINGER_R,""
MINI_GUNNER_WEAR_FINGER_L,""
MINI_GUNNER_WEAR_NECK_1,""
MINI_GUNNER_WEAR_NECK_2,""
MINI_GUNNER_WEAR_BODY,"objects/armor/vanguard-spiked-vest.yml"
MINI_GUNNER_WEAR_HEAD,"objects/armor/ballistic-helmet.yml"
MINI_GUNNER_WEAR_LEGS,""
MINI_GUNNER_WEAR_FEET,"objects/armor/phagia-corps-ballistic-boots.yml"
MINI_GUNNER_WEAR_HANDS,"objects/armor/weight-lifting-gloves.yml"
MINI_GUNNER_WEAR_ARMS,""
MINI_GUNNER_WEAR_SHIELD,""
MINI_GUNNER_WEAR_ABOUT,""
MINI_GUNNER_WEAR_WAIST,""
MINI_GUNNER_WEAR_WRIST_R,""
MINI_GUNNER_WEAR_WRIST_L,""
MINI_GUNNER_WEAR_PRIMARY,"objects/rifle/belt-fed-minigun.yml"
MINI_GUNNER_WEAR_WIELD,"objects/rifle/belt-fed-minigun.yml"
MINI_GUNNER_WEAR_HOLD,""
MINI_GUNNER_WEAR_SECONDARY_WEAPON,""
MINI_GUNNER_WEAR_SECONDARY,""
MINI_GUNNER_WEAR_WEAPON_ATTACHMENT,"objects/attachment/belt-feeder.yml"
MINI_GUNNER_WEAR_SHOULDERS_L,"objects/armor/vanguard-shoulder-pad.yml"
MINI_GUNNER_WEAR_SHOULDERS_R,"objects/armor/vanguard-shoulder-pad.yml"
MINI_GUNNER_WEAR_BACKPACK,"objects/armor/ammo-backpack.yml"
MINI_GUNNER_WEAR_GOGGLES,"objects/armor/ballistic-eye-gaurd.yml"
MINI_GUNNER_WEAR_VEST_PACK,""
MINI_GUNNER_WEAR_ELBOW_L,""
MINI_GUNNER_WEAR_ELBOW_R,"objects/armor/vanguard-elbow-guard.yml"
LOWLY_SECURITY_GUARD_WEAR_LIGHT,""
LOWLY_SECURITY_GUARD_WEAR_FINGER_R,""
LOWLY_SECURITY_GUARD_WEAR_FINGER_L,""
LOWLY_SECURITY_GUARD_WEAR_NECK_1,""
LOWLY_SECURITY_GUARD_WEAR_NECK_2,""
LOWLY_SECURITY_GUARD_WEAR_BODY,"objects/armor/basic-ballistic-vest.yml"
LOWLY_SECURITY_GUARD_WEAR_HEAD,""
LOWLY_SECURITY_GUARD_WEAR_LEGS,""
LOWLY_SECURITY_GUARD_WEAR_FEET,"objects/armor/basic-boots.yml"
LOWLY_SECURITY_GUARD_WEAR_HANDS,""
LOWLY_SECURITY_GUARD_WEAR_ARMS,""
LOWLY_SECURITY_GUARD_WEAR_SHIELD,""
LOWLY_SECURITY_GUARD_WEAR_ABOUT,""
LOWLY_SECURITY_GUARD_WEAR_WAIST,""
LOWLY_SECURITY_GUARD_WEAR_WRIST_R,""
LOWLY_SECURITY_GUARD_WEAR_WRIST_L,""
LOWLY_SECURITY_GUARD_WEAR_PRIMARY,"objects/rifle/hk45.yml"
LOWLY_SECURITY_GUARD_WEAR_WIELD,""
LOWLY_SECURITY_GUARD_WEAR_HOLD,"objects/gadget/cbradio.yml"
LOWLY_SECURITY_GUARD_WEAR_SECONDARY_WEAPON,""
LOWLY_SECURITY_GUARD_WEAR_SECONDARY,""
LOWLY_SECURITY_GUARD_WEAR_WEAPON_ATTACHMENT,""
LOWLY_SECURITY_GUARD_WEAR_SHOULDERS_L,""
LOWLY_SECURITY_GUARD_WEAR_SHOULDERS_R,""
LOWLY_SECURITY_GUARD_WEAR_BACKPACK,""
LOWLY_SECURITY_GUARD_WEAR_GOGGLES,""
LOWLY_SECURITY_GUARD_WEAR_VEST_PACK,""
LOWLY_SECURITY_GUARD_WEAR_ELBOW_L,""
LOWLY_SECURITY_GUARD_WEAR_ELBOW_R,""
LUNATIC_WEAR_LIGHT,""
LUNATIC_WEAR_FINGER_R,""
LUNATIC_WEAR_FINGER_L,"objects/armor/spiked-skull-ring.yml"
LUNATIC_WEAR_NECK_1,"objects/armor/qi-wol-clock-chain.yml"
LUNATIC_WEAR_NECK_2,""
LUNATIC_WEAR_BODY,"objects/armor/weak-tanktop.yml"
LUNATIC_WEAR_HEAD,"objects/armor/generic-hat.yml"
LUNATIC_WEAR_LEGS,"objects/armor/generic-red-jeans.yml"
LUNATIC_WEAR_FEET,"objects/armor/iconic-shoes.yml"
LUNATIC_WEAR_HANDS,""
LUNATIC_WEAR_ARMS,""
LUNATIC_WEAR_SHIELD,""
LUNATIC_WEAR_ABOUT,""
LUNATIC_WEAR_WAIST,"objects/armor/plain-black-belt.yml"
LUNATIC_WEAR_WRIST_R,""
LUNATIC_WEAR_WRIST_L,""
LUNATIC_WEAR_PRIMARY,"objects/rifle/uzi-machine-pistol.yml"
LUNATIC_WEAR_WIELD,"objects/rifle/uzi-machine-pistol.yml"
LUNATIC_WEAR_HOLD,""
LUNATIC_WEAR_SECONDARY_WEAPON,""
LUNATIC_WEAR_SECONDARY,""
LUNATIC_WEAR_WEAPON_ATTACHMENT,"objects/attachment/high-velocity-magazine.yml"
LUNATIC_WEAR_SHOULDERS_L,""
LUNATIC_WEAR_SHOULDERS_R,""
LUNATIC_WEAR_BACKPACK,""
LUNATIC_WEAR_GOGGLES,"objects/armor/idiots-sunglasses.yml"
LUNATIC_WEAR_VEST_PACK,""
LUNATIC_WEAR_ELBOW_L,""
LUNATIC_WEAR_ELBOW_R,""
MSG_CRITICAL,"{red}***CRITICAL***{/red} --"
MSG_HEADSHOT,"{red}***HEADSHOT***{/red} -- "
MSG_HIT_BY_HEADSHOT,"{red}*** YOU'VE BEEN HEADSHOTTED ***{/red} -- "
MSG_HIT,"{yel}--[HIT]--{/yel}"
MSG_OUT_OF_AMMO,"{gld}*CLICK*{/gld} Your weapon is out of ammo!"
MSG_MISSED_TARGET,"You missed your target!"
MSG_TARGET_DEAD,"It appears that your target is dead."
MSG_YOURE_INJURED,"You are injured!"
MSG_YOU_ARE_DISORIENTED,"You become disoriented!"
MSG_YOU_DISORIENT_SOMEONE,"You disorient your target!"
MSG_FIRE_DAMAGE,"[%d] You suffer burns from the roaring fire!\r\n"
MSG_EXPLOSIVE_DAMAGE,"[%d] You take EXPLOSIVE damage!\r\n"
MSG_SHRAPNEL_DAMAGE,"[%d] You are shredded by SHRAPNEL!\r\n"
MSG_CORROSIVE_DAMAGE,"[%d] You take CORROSIVE damage!\r\n"
MSG_CRYOGENIC_DAMAGE,"[%d] You take CRYOGENIC damage!\r\n"
MSG_RADIOACTIVE_DAMAGE,"[%d] You take RADIOACTIVE damage!\r\n"
MSG_ANTI_MATTER_DAMAGE,"[%d] You take ANTI-MATTER damage!\r\n"
MSG_EMP_DAMAGE,"[%d] You take EMP damage!\r\n"
MSG_SHOCK_DAMAGE,"[%d] You take SHOCK damage!\r\n"
MSG_SMOKE_DAMAGE,"[%d] You struggle to breath as smoke fills your lungs!\r\n"
MSG_NARROWLY_MISSED_ME,"You just barely get out of the way of a potentially fatal shot!\r\n"
MSG_YOU_GOT_HIT_BY_INCENDIARY_AMMO,"{yel} Your equipment burns from incendiary damage! {/yel}"
MSG_YOU_INFLICTED_INCENDIARY_AMMO,"{grn} You inflict incendiary damage on your target! {/grn}"
MSG_YOU_ARE_INJURED,"{red}***YOU ARE INJURED***{/red} --"
MSG_YOUR_TARGET_IS_DEAD,"{grn}*** YOUR TARGET IS DEAD ***{/grn}\r\n"
MSG_HIT_BY_RIFLE_ATTACK,"{red}*** YOU ARE HIT ***{/red} -- "
MSG_HIT_BY_MELEE_ATTACK,"{red}*** YOU ARE HIT BY A MELEE WEAPON ***{/red} -- "
MSG_HIT_BY_BLADED_MELEE_ATTACK,"{red}*** YOU ARE HIT BY A BLADED WEAPON ***{/red} -- "
MSG_HIT_BY_BLUNT_MELEE_ATTACK,"{red}*** YOU ARE HIT BY A BLUNT FORCE WEAPON ***{/red} -- "
MSG_YOU_INFLICTED_MELEE_ATTACK,"{red}*** YOU INFLICTED MELEE DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_BLADED_MELEE_ATTACK,"{red}*** YOU INFLICTED BLADED WEAPON DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_BLUNT_MELEE_ATTACK,"{red}*** YOU INFLICTED BLUNT FORCE WEAPON DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_INCENDIARY_DAMAGE,"{red}*** YOU INFLICTED {yel}INCENDIARY{/yel}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_RADIOACTIVE_DAMAGE,"{red}*** YOU INFLICTED {grn}RADIOACTIVE{/blu}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_ANTI_MATTER_DAMAGE,"{red}*** YOU INFLICTED {blu}ANTI-MATTER{/blu}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_CORROSIVE_DAMAGE,"{red}*** YOU INFLICTED {grn}CORROSIVE{/grn}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_EMP_DAMAGE,"{red}*** YOU INFLICTED {blu}EMP{/blu}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_EXPLOSIVE_DAMAGE,"{red}*** YOU INFLICTED {yel}EXPLOSIVE{/yel}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_SHRAPNEL_DAMAGE,"{red}*** YOU INFLICTED {blu}SHRAPNEL{/blu}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_CRYOGENIC_DAMAGE,"{red}*** YOU INFLICTED {blu}CRYOGENIC{/blu}{red} DAMAGE ***{/red} -- "
MSG_YOU_INFLICTED_SHOCK_DAMAGE,"{red}*** YOU INFLICTED {blu}SHOCK{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_INCENDIARY_DAMAGE,"{red}*** YOU TAKE {yel}INCENDIARY{/yel}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_RADIOACTIVE_DAMAGE,"{red}*** YOU TAKE {grn}RADIOACTIVE{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_ANTI_MATTER_DAMAGE,"{red}*** YOU TAKE {blu}ANTI-MATTER{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_CORROSIVE_DAMAGE,"{red}*** YOU TAKE {grn}CORROSIVE{/grn}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_EMP_DAMAGE,"{red}*** YOU TAKE {blu}EMP{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_EXPLOSIVE_DAMAGE,"{red}*** YOU TAKE {yel}EXPLOSIVE{/yel}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_SHRAPNEL_DAMAGE,"{red}*** YOU TAKE {blu}SHRAPNEL{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_CRYOGENIC_DAMAGE,"{red}*** YOU TAKE {blu}CRYOGENIC{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_SHOCK_DAMAGE,"{red}*** YOU TAKE {blu}SHOCK{/blu}{red} DAMAGE ***{/red} -- "
MSG_HIT_BY_SPRAY_ATTACK,"{red}*** YOU ARE HIT BY A SPRAY OF BULLETS ***{/red} -- "
MSG_TARGET_IN_PEACEFUL_ROOM,"{gld}Your target is in a peaceful room{/gld}"
MSG_NO_PRIMARY_WIELDED,"{gld}You aren't wielding a primary weapon.{/gld}"
MSG_COOLDOWN_IN_EFFECT,"{gld}Weapon cooldown in effect.{/gld}"
MSG_COULDNT_FIND_TARGET,"You couldn't find your target!"
MINI_GUNNER_RANDOM_ATTACK_YELL_STRINGS,""
MINI_GUNNER_RANDOM_DISORIENT_STRINGS,""
MSG_YOU_INJURED_SOMEONE,"{red}*** YOU INJURED YOUR TARGET ***{/red}!"
DEFAULT_PUBLIC_CHANNELS,"chat,gossip,gratz,newbie"
EXTENDED_PREFERENCES,IMPLODE({"nochat","nogossip","nonewbie","nogratz"},"|")
EXTENDED_PREFERENCES_DEFAULTS,IMPLODE({"0","0","0","0"},"|")
SUPER_USERS_LIST,IMPLODE({"far"},"|")
PRIMARY_CHOICE_SCREEN_PSG1_DESCRIPTION,"A bolt-action semi-automatic sniper rifle.\r\n"
PRIMARY_CHOICE_SCREEN_L96AW_DESCRIPTION,"A reliable semi-automatic sniper rifle that works well in very cold conditions.\r\n"
PRIMARY_CHOICE_SCREEN_M16A4_DESCRIPTION,"Standard issue marine corps automatic rifle.\r\n"
PRIMARY_CHOICE_SCREEN_M4_DESCRIPTION,"Lighter and shorter variant of the M16A2.\r\n"
PRIMARY_CHOICE_SCREEN_MP5_DESCRIPTION,"Widely used in SWAT teams across the world,the MP5 is *the* SMG for tactical operations.\r\n"
PRIMARY_CHOICE_SCREEN_SASG12_DESCRIPTION,"Semi-automatic shotgun with large spread,but limited range.\r\n"
PRIMARY_CHOICE_SCREEN_M3_DESCRIPTION,"A dual-mode shotgun with pump-action and semi-automatic modes.\r\n"
PRIMARY_CHOICE_SCREEN_FAMAS_DESCRIPTION,"Assault rifle known for it's high rate of fire.\r\n"
PRIMARY_CHOICE_SCREEN_FMG9_DESCRIPTION,"A new prototype of foldable machine guns.\r\n"
PRIMARY_CHOICE_SCREEN_P90_DESCRIPTION,"Assault rifle known for it's high rate of fire.\r\n"
PRIMARY_CHOICE_SCREEN_AUGPARA_DESCRIPTION,"A sub-machine-gun form of the popular AUG-A3 assault rifle.\r\n"
PRIMARY_CHOICE_SCREEN_TAR21_DESCRIPTION,"The TAR-21 is a reliable assault rifle with two firing modes.\r\n"
PRIMARY_CHOICE_SCREEN_SCARH_DESCRIPTION,"Gas-operated assault rifle used by SOCOM operatives.\r\n"
PRIMARY_CHOICE_SCREEN_UMP45_DESCRIPTION,"Dubbed the 'Universal Sub Machinegun',the UMP-45 is a versatile and reliable SMG.\r\n"
PRIMARY_CHOICE_SCREEN_MK46_DESCRIPTION,"The MK-46 LMG is a perfect balance of firepower,portability,and accuracy.\r\n"
PRIMARY_CHOICE_SCREEN_HK21_DESCRIPTION,"General purpose LMG widely used in tactical teams all over the world.\r\n"
MSG_YOU_GOT_HIT_BY_REFLECTED_MUNTIONS,"*** [ You are HIT by {red} REFLECTED MUNITIONS {/red}] *** "
MSG_YOU_REFLECTED_MUNITIONS,"*** [ You {grn} REFLECTED part of that attack {/grn}] *** "
MSG_YOU_INFLICTED_AR_SHRAPNEL,"{grn}*** [ You INFLICTED A.R. ::SHRAPNEL:: ] *** {/grn}"
MSG_YOU_GOT_HIT_BY_AR_SHRAPNEL,"{red}*** [ You got hit by A.R. ::SHRAPNEL:: ] *** {/red}"
SUPER_USER_REJECT_MESSAGE,"{red}You are not a super user.\r\nA man with no teeth spits on you.{/red}"
ADMIN_SUCCESS_MESSAGE,"{grn}[+] It is done.{/grn}"
ADMIN_FAILURE_MESSAGE,"{red}[-] Failure.{/red}"
UNIMPLEMENTED_MESSAGE,"{red}this command is unimplemented{/red}"
STOCK_STARS_MESSAGE,"You can't see anything but stars!"
STOCK_BLIND_MESSAGE,"You can't see a damned thing,you're blind!"
STOCK_PITCH_BLACK_MESSAGE,"It is pitch black..."
STOCK_READ_WHAT_MESSAGE,"Read what?"
STOCK_EXAMINE_MESSAGE,"Examine what?"
STOCK_LOOK_INSIDE_MESSAGE,"When you look inside,you see:"
STOCK_GOLD_BROKE_MESSAGE,"You're broke!"
STOCK_GOLD_ONE_MISERABLE_MESSAGE,"You have one miserable little gold coin."
STOCK_GOLD_PREFIX_MESSAGE,"You have "
STOCK_GOLD_SUFFIX_MESSAGE," gold coins."
MSG_YOU_FEIGN_DEATH,"You succesfully feign death. The enemy is none the wiser..."
MSG_YOU_FAIL_FEIGN_DEATH,"You fail at feigning death...\r\nYou are on the ground and vulnerable!"
ADVANCE_LEVEL_CONGRATS,"{grn}Congratulations on advancing,soldier! You are proving to be a well-rounded member of the {blu}Counter Terrorist Unit{/blu}."
CHARGEN_TRIADS_FORMAT,"Melee: %d\r\nWeapons: %d\r\nIntel: %d\r\nSpeed: %d\r\nArmor: %d\r\n"
ADVANCE_LEVEL_MESSAGE,"{grn}CONGRATS! You rise a level!{/grn}"
ADVANCE_MULTIPLE_LEVELS_MESSAGE,"{grn}CONGRATS! You rise %d levels!{/grn}"

[uint8_t]
RADIO_INITIAL_RESPONSE_TICKS,10
SNIPER_TRACKING_SHOT_MAX_COUNT,1
LUCKY_DISORIENTED_VISION_CHANCE,2
PERCENT_CHANCE_DISSIPATED_DETECTED_BY_THERMALS,5
ENGINEER_REPLENISH_PULSE,3
ENGINEER_SENSOR_GRENADE_MAX_COUNT,2
ENGINEER_DRONE_BOMB_CHARGE_MAX_COUNT,3
SNIPER_REPLENISH_PULSE,3
SNIPER_CLAYMORE_MAX_COUNT,1
GHOST_REPLENISH_PULSE,5
GHOST_DISSIPATE_CHARGE_MAX_COUNT,2
PYREXIA_REPLENISH_PULSE,5
FORGE_REPLENISH_PULSE,5
SYNDROME_REPLENISH_PULSE,5
GHOST_CLAYMORE_MAX_COUNT,2
CAMERA_INSTALLATION_TICS,30
CLAYMORE_INSTALLATION_TICS,10
PYREXIA_FIRE_NADE_CHARGES_DEFAULT,3
PYREXIA_FIRE_NADE_CHARGES_INITIATE,3
PYREXIA_FIRE_NADE_CHARGES_FAMILIAR,6
PYREXIA_FIRE_NADE_CHARGES_MASTER,9
SINGLE_SHOT_SHOTGUN,1
SINGLE_SHOT_ASSAULT_RIFLE,3
SINGLE_SHOT_SUB_MACHINE_GUN,3
SINGLE_SHOT_SNIPER,1
SINGLE_SHOT_HANDGUN,1
SINGLE_SHOT_PISTOL,1
SINGLE_SHOT_MACHINE_PISTOL,6
SINGLE_SHOT_LIGHT_MACHINE_GUN,8
SPRAY_SHOT_SHOTGUN,2
SPRAY_SHOT_ASSAULT_RIFLE,9
SPRAY_SHOT_SUB_MACHINE_GUN,6
SPRAY_SHOT_SNIPER,1
SPRAY_SHOT_HANDGUN,1
SPRAY_SHOT_PISTOL,1
SPRAY_SHOT_MACHINE_PISTOL,12
SPRAY_SHOT_LIGHT_MACHINE_GUN,16
SPRAY_CHANCE,25
SPRAY_HEADSHOT_CHANCE,3
SPRAY_CRITICAL_CHANCE,2
SPRAY_CRITICAL_REDUCTION_DIVISOR,10
REVIVE_TICKS,40
REVIVE_HP,50
INJURED_HP,5
LOWLY_SECURITY_SCAN_DEPTH,1
MINI_GUNNER_SCAN_DEPTH,5
SPRAY_CHANCE_SKILL_MODIFIER,17
HEADSHOT_SKILL_MODIFIER,5
ASSAULT_RIFLE_SHRAPNEL_SKILL_CHANCE,10
ASSAULT_RIFLE_SHRAPNEL_SKILL_DICE_COUNT,3
ASSAULT_RIFLE_SHRAPNEL_SKILL_DICE_SIDES,30
SHOW_UNIMPLEMENTED_SKILLS,1
GHOST_FEIGN_DEATH_INITIATE_DURATION,33
GHOST_FEIGN_DEATH_FAMILIAR_DURATION,66
GHOST_FEIGN_DEATH_MASTER_DURATION,99
MARKSMAN_CLASS_TRIADS_MELEE,1
GHOST_CLASS_TRIADS_MELEE,1
GHOST_CLASS_TRIADS_WEAPONS,3
GHOST_CLASS_TRIADS_INTEL,2
GHOST_CLASS_TRIADS_SPEED,1
GHOST_CLASS_TRIADS_ARMOR,3
MARKSMAN_CLASS_TRIADS_WEAPONS,3
MARKSMAN_CLASS_TRIADS_INTEL,2
MARKSMAN_CLASS_TRIADS_SPEED,2
MARKSMAN_CLASS_TRIADS_ARMOR,2
BANDIT_CLASS_TRIADS_MELEE,2
BANDIT_CLASS_TRIADS_WEAPONS,2
BANDIT_CLASS_TRIADS_INTEL,3
BANDIT_CLASS_TRIADS_SPEED,3
BANDIT_CLASS_TRIADS_ARMOR,1
BUTCHER_CLASS_TRIADS_MELEE,3
BUTCHER_CLASS_TRIADS_WEAPONS,2
BUTCHER_CLASS_TRIADS_INTEL,2
BUTCHER_CLASS_TRIADS_SPEED,2
BUTCHER_CLASS_TRIADS_ARMOR,2
STRIKER_CLASS_TRIADS_MELEE,3
STRIKER_CLASS_TRIADS_WEAPONS,3
STRIKER_CLASS_TRIADS_INTEL,1
STRIKER_CLASS_TRIADS_SPEED,3
STRIKER_CLASS_TRIADS_ARMOR,1
OBSTRUCTOR_CLASS_TRIADS_MELEE,3
OBSTRUCTOR_CLASS_TRIADS_WEAPONS,2
OBSTRUCTOR_CLASS_TRIADS_INTEL,2
OBSTRUCTOR_CLASS_TRIADS_SPEED,1
OBSTRUCTOR_CLASS_TRIADS_ARMOR,3
MALADY_CLASS_TRIADS_MELEE,2
MALADY_CLASS_TRIADS_WEAPONS,2
MALADY_CLASS_TRIADS_INTEL,3
MALADY_CLASS_TRIADS_SPEED,2
MALADY_CLASS_TRIADS_ARMOR,2
PYREXIA_CLASS_TRIADS_MELEE,1
PYREXIA_CLASS_TRIADS_WEAPONS,3
PYREXIA_CLASS_TRIADS_INTEL,3
PYREXIA_CLASS_TRIADS_SPEED,3
PYREXIA_CLASS_TRIADS_ARMOR,1
DEALER_CLASS_TRIADS_MELEE,1
DEALER_CLASS_TRIADS_WEAPONS,3
DEALER_CLASS_TRIADS_INTEL,3
DEALER_CLASS_TRIADS_SPEED,1
DEALER_CLASS_TRIADS_ARMOR,3
FORGE_CLASS_TRIADS_MELEE,2
FORGE_CLASS_TRIADS_WEAPONS,2
FORGE_CLASS_TRIADS_INTEL,3
FORGE_CLASS_TRIADS_SPEED,2
FORGE_CLASS_TRIADS_ARMOR,2
SYNDROME_CLASS_TRIADS_MELEE,1
SYNDROME_CLASS_TRIADS_WEAPONS,3
SYNDROME_CLASS_TRIADS_INTEL,3
SYNDROME_CLASS_TRIADS_SPEED,3
SYNDROME_CLASS_TRIADS_ARMOR,1
MACHINIST_CLASS_TRIADS_MELEE,2
MACHINIST_CLASS_TRIADS_WEAPONS,2
MACHINIST_CLASS_TRIADS_INTEL,3
MACHINIST_CLASS_TRIADS_SPEED,1
MACHINIST_CLASS_TRIADS_ARMOR,3
REGENERATED_AMMO_LOW,5
REGENERATED_AMMO_HIGH,15
RELOAD_TICKS_SHOTGUN,3
RELOAD_TICKS_ASSAULT_RIFLE,6
RELOAD_TICKS_SUB_MACHINE_GUN,2
RELOAD_TICKS_SNIPER,2
RELOAD_TICKS_HANDGUN,2
RELOAD_TICKS_PISTOL,2
RELOAD_TICKS_MACHINE_PISTOL,2
RELOAD_TICKS_LIGHT_MACHINE_GUN,16
DEFAULT_DISORIENT_TICKS_FROM_RIFLE_ATTACK,16

[uint32_t]
BREACHER_REPLENISH_CALL_COUNT,1
GHOST_DISSIPATE_TICKS_DURATION,20
SNIPER_XRAY_SHOT_MAX_COUNT,10
