#ifndef __MENTOC_MODS_WEAPON_STAT_LIST_HEADER__
#define __MENTOC_MODS_WEAPON_STAT_LIST_HEADER__

/** fields are allowable, accuracy, damage */
	static inline weapon_stat_list_t* weapon_stats(int type){
		static weapon_stat_list_t shotgun = {
			{WSL_SHOTGUN_0_ALLOWABLE(),WSL_SHOTGUN_0_ACCURACY(),WSL_SHOTGUN_0_DAMAGE()},
			{WSL_SHOTGUN_1_ALLOWABLE(),WSL_SHOTGUN_1_ACCURACY(),WSL_SHOTGUN_1_DAMAGE()},
			{WSL_SHOTGUN_2_ALLOWABLE(),WSL_SHOTGUN_2_ACCURACY(),WSL_SHOTGUN_2_DAMAGE()},
			{WSL_SHOTGUN_3_ALLOWABLE(),WSL_SHOTGUN_3_ACCURACY(),WSL_SHOTGUN_3_DAMAGE()},
			{WSL_SHOTGUN_4_ALLOWABLE(),WSL_SHOTGUN_4_ACCURACY(),WSL_SHOTGUN_4_DAMAGE()}
		};
		static weapon_stat_list_t ar = {
			{WSL_AR_0_ALLOWABLE(),WSL_AR_0_ACCURACY(),WSL_AR_0_DAMAGE()},
			{WSL_AR_1_ALLOWABLE(),WSL_AR_1_ACCURACY(),WSL_AR_1_DAMAGE()},
			{WSL_AR_2_ALLOWABLE(),WSL_AR_2_ACCURACY(),WSL_AR_2_DAMAGE()},
			{WSL_AR_3_ALLOWABLE(),WSL_AR_3_ACCURACY(),WSL_AR_3_DAMAGE()},
			{WSL_AR_4_ALLOWABLE(),WSL_AR_4_ACCURACY(),WSL_AR_4_DAMAGE()}
		};
		static weapon_stat_list_t smg = {
			{WSL_SMG_0_ALLOWABLE(),WSL_SMG_0_ACCURACY(),WSL_SMG_0_DAMAGE()},
			{WSL_SMG_1_ALLOWABLE(),WSL_SMG_1_ACCURACY(),WSL_SMG_1_DAMAGE()},
			{WSL_SMG_2_ALLOWABLE(),WSL_SMG_2_ACCURACY(),WSL_SMG_2_DAMAGE()},
			{WSL_SMG_3_ALLOWABLE(),WSL_SMG_3_ACCURACY(),WSL_SMG_3_DAMAGE()},
			{WSL_SMG_4_ALLOWABLE(),WSL_SMG_4_ACCURACY(),WSL_SMG_4_DAMAGE()}
		};
		static weapon_stat_list_t machine_pistol = {
			{WSL_MACHINE_PISTOL_0_ALLOWABLE(),WSL_MACHINE_PISTOL_0_ACCURACY(),WSL_MACHINE_PISTOL_0_DAMAGE()},
			{WSL_MACHINE_PISTOL_1_ALLOWABLE(),WSL_MACHINE_PISTOL_1_ACCURACY(),WSL_MACHINE_PISTOL_1_DAMAGE()},
			{WSL_MACHINE_PISTOL_2_ALLOWABLE(),WSL_MACHINE_PISTOL_2_ACCURACY(),WSL_MACHINE_PISTOL_2_DAMAGE()},
			{WSL_MACHINE_PISTOL_3_ALLOWABLE(),WSL_MACHINE_PISTOL_3_ACCURACY(),WSL_MACHINE_PISTOL_3_DAMAGE()},
			{WSL_MACHINE_PISTOL_4_ALLOWABLE(),WSL_MACHINE_PISTOL_4_ACCURACY(),WSL_MACHINE_PISTOL_4_DAMAGE()}
		};
		static weapon_stat_list_t handgun = {
			{WSL_HANDGUN_0_ALLOWABLE(),WSL_HANDGUN_0_ACCURACY(),WSL_HANDGUN_0_DAMAGE()},
			{WSL_HANDGUN_1_ALLOWABLE(),WSL_HANDGUN_1_ACCURACY(),WSL_HANDGUN_1_DAMAGE()},
			{WSL_HANDGUN_2_ALLOWABLE(),WSL_HANDGUN_2_ACCURACY(),WSL_HANDGUN_2_DAMAGE()},
			{WSL_HANDGUN_3_ALLOWABLE(),WSL_HANDGUN_3_ACCURACY(),WSL_HANDGUN_3_DAMAGE()},
			{WSL_HANDGUN_4_ALLOWABLE(),WSL_HANDGUN_4_ACCURACY(),WSL_HANDGUN_4_DAMAGE()}
		};
		static weapon_stat_list_t lmg = {
			{WSL_LMG_0_ALLOWABLE(),WSL_LMG_0_ACCURACY(),WSL_LMG_0_DAMAGE()},
			{WSL_LMG_1_ALLOWABLE(),WSL_LMG_1_ACCURACY(),WSL_LMG_1_DAMAGE()},
			{WSL_LMG_2_ALLOWABLE(),WSL_LMG_2_ACCURACY(),WSL_LMG_2_DAMAGE()},
			{WSL_LMG_3_ALLOWABLE(),WSL_LMG_3_ACCURACY(),WSL_LMG_3_DAMAGE()},
			{WSL_LMG_4_ALLOWABLE(),WSL_LMG_4_ACCURACY(),WSL_LMG_4_DAMAGE()}
		};
		static weapon_stat_list_t sniper = {
			{WSL_SNIPER_0_ALLOWABLE(),WSL_SNIPER_0_ACCURACY(),WSL_SNIPER_0_DAMAGE()},
			{WSL_SNIPER_1_ALLOWABLE(),WSL_SNIPER_1_ACCURACY(),WSL_SNIPER_1_DAMAGE()},
			{WSL_SNIPER_2_ALLOWABLE(),WSL_SNIPER_2_ACCURACY(),WSL_SNIPER_2_DAMAGE()},
			{WSL_SNIPER_3_ALLOWABLE(),WSL_SNIPER_3_ACCURACY(),WSL_SNIPER_3_DAMAGE()},
			{WSL_SNIPER_4_ALLOWABLE(),WSL_SNIPER_4_ACCURACY(),WSL_SNIPER_4_DAMAGE()}
		};
		static weapon_stat_list_t empty = {
			{0,0,0},
			{0,0,0},
			{0,0,0},
			{0,0,0},
			{0,0,0}
		};
		switch(static_cast<weapon_rifle_t>(type)){
			case weapon_rifle_t::HANDGUN:
			case weapon_rifle_t::PISTOL:
				return &handgun;
			case weapon_rifle_t::SHOTGUN: 
				return &shotgun;
			case weapon_rifle_t::ASSAULT_RIFLE:
				return &ar;
			case weapon_rifle_t::SUB_MACHINE_GUN:
				return &smg;
			case weapon_rifle_t::MACHINE_PISTOL:
				return &machine_pistol;
			case weapon_rifle_t::LIGHT_MACHINE_GUN:
				return &lmg;
			case weapon_rifle_t::SNIPER:
				return &sniper;
			default:
				return &empty;
		}
	}//end stat list func
#endif
