ALTER TABLE object_gadget ADD COLUMN exit_key INTEGER NOT NULL DEFAULT 0;
ALTER TABLE object_gadget ADD COLUMN min_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE object_gadget ADD COLUMN worth INTEGER NOT NULL DEFAULT 0;

ALTER TABLE object_armor ADD COLUMN hp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE object_armor ADD COLUMN classification VARCHAR(8) NOT NULL DEFAULT 'BASIC';
ALTER TABLE object_armor ADD COLUMN worth INTEGER NOT NULL DEFAULT 0;
