ALTER TABLE object ALTER COLUMN obj_flags DROP NOT NULL;
ALTER TABLE object ALTER COLUMN obj_name DROP NOT NULL;
ALTER TABLE object ALTER COLUMN obj_short_description DROP NOT NULL;
ALTER TABLE object ALTER COLUMN obj_belongs_to_player DROP NOT NULL;
ALTER TABLE object ALTER COLUMN obj_file TYPE VARCHAR(255);
ALTER TABLE object ALTER COLUMN obj_file SET NOT NULL;
ALTER TABLE object ALTER COLUMN obj_type SET NOT NULL;
