CREATE TABLE object_flags (
	id SERIAL,
	obj_fk_id INTEGER NOT NULL,
	value_0 INTEGER NOT NULL,
	value_1 INTEGER NOT NULL,
	value_2 INTEGER NOT NULL,
	value_3 INTEGER NOT NULL,
	type_flag INTEGER NOT NULL,
	wear_flags INTEGER NOT NULL,
	extra_flags INTEGER NOT NULL,
	weight INTEGER NOT NULL,
	cost INTEGER NOT NULL,
	cost_per_day INTEGER NOT NULL,
	timer INTEGER NOT NULL,
	bitvector INTEGER NOT NULL
);
